services:
  google-maps-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - gmapsdata:/gmapsdata
    command: ["-data-folder", "/gmapsdata"]

volumes:
  gmapsdev:

networks:
  coolify:
    external: true
