services:
  google-maps-scraper:
    ports:
      - "7474:8080"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - gmapsdata:/gmapsdata
    command: ["-data-folder", "/gmapsdata"]

volumes:
  gmapsdev:
